// flow-typed signature: d14b67e169640f84e9c313b3d944c967
// flow-typed version: <<STUB>>/arrify_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'arrify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'arrify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'arrify/index' {
  declare module.exports: $Exports<'arrify'>;
}
declare module 'arrify/index.js' {
  declare module.exports: $Exports<'arrify'>;
}
