// flow-typed signature: 141475cbec5c1e9c9e1f3c7cf62b7895
// flow-typed version: <<STUB>>/eslint-plugin-markdown_v^1.0.0-beta.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-markdown/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-markdown/lib/processor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-markdown/index' {
  declare module.exports: $Exports<'eslint-plugin-markdown'>;
}
declare module 'eslint-plugin-markdown/index.js' {
  declare module.exports: $Exports<'eslint-plugin-markdown'>;
}
declare module 'eslint-plugin-markdown/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-markdown/lib/index'>;
}
declare module 'eslint-plugin-markdown/lib/processor.js' {
  declare module.exports: $Exports<'eslint-plugin-markdown/lib/processor'>;
}
