// flow-typed signature: ffd703d77a29d94b2eae66d4955b1d68
// flow-typed version: <<STUB>>/eslint-config-fb-strict_v^20.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fb-strict'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fb-strict' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-fb-strict/index' {
  declare module.exports: $Exports<'eslint-config-fb-strict'>;
}
declare module 'eslint-config-fb-strict/index.js' {
  declare module.exports: $Exports<'eslint-config-fb-strict'>;
}
