// flow-typed signature: 88836153b78bb6759f97b929643603b0
// flow-typed version: <<STUB>>/powerset_v^0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'powerset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'powerset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'powerset/powerset' {
  declare module.exports: any;
}

declare module 'powerset/test/test-all' {
  declare module.exports: any;
}

// Filename aliases
declare module 'powerset/powerset.js' {
  declare module.exports: $Exports<'powerset/powerset'>;
}
declare module 'powerset/test/test-all.js' {
  declare module.exports: $Exports<'powerset/test/test-all'>;
}
